routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('pages.home');
//});
//
//Route::get('/', function () {
//    return view('welcome');
//});

//Route::get('/', function() {
//    return view('pages.home');
//});
//
////
//Route::get('about', function()
//{
//
//    return View::make('pages.contact');
//
//});
//
//

//Route::get('/', ['as' => 'index', 'uses' => 'RulesController@index']);
//Route::get('/data-sets/upload', ['as' => 'upload', 'uses' => 'RulesController@index']);


Route::group(['as' => 'arules.', 'prefix' => '/'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'RulesController@index']);
    Route::get('/data-sets/import', ['as' => 'import', 'uses' => 'DatasetController@index']);
    Route::post('/data-sets/send', ['as' => 'import_data', 'uses' => 'DatasetController@importDataSet']);
    Route::get('/data-sets/list', ['as' => 'list_data', 'uses' => 'DatasetController@listDatasets']);
    Route::get('/data-sets/sample-one', ['as' => 'sample_one', 'uses' => 'DatasetController@sampleOneAssociation']);
    Route::get('/data-sets/sample-two', ['as' => 'sample_two', 'uses' => 'DatasetController@sampleTwoAssociation']);

    Route::get('/data-sets/{slug}', ['as' => 'predict', 'uses' => 'DatasetController@predictAssociation']);
    Route::post('/data-sets/{slug}', ['as' => 'adjust_predict', 'uses' => 'DatasetController@AdjustPredictAssociation']);


});

resources/views/includes/footer.blade.php
<div class="py-5" id="copyright text-right">© Copyright {{date('Y')}} Association rule | All right reserved </div>
<script src="{{asset('js/app.js')}}"></script>

<script>
    // $.ajaxSetup({
    //     headers: {
    //         'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    //     }
    // });
</script>

resources/views/includes/head.blade.php
<meta charset="utf-8">

<meta name="description" content="">

<meta name="" content="Blade">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-token" content="{{ csrf_token() }}">

<title>Association Rule - @yield('title')</title>

<!-- load bootstrap from a cdn -->

{{--<link rel="stylesheet" href="//netdna.bootstrapcdn.com/twitter-bootstrap/3.0.3/css/bootstrap-combined.min.css">--}}
<link rel="stylesheet" type="text/css" href="{{asset('css/app.css')}}">
<style>
    .main{
        min-height: 70vh;
    }
    .footer{
        background-color: #343a40 !important;
        text-align: center;
        color: white;
    }
</style>

resources/views/includes/header.blade.php
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">Association Rule</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{route('arules.index')}}">Home <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Get started
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{route('arules.import')}}">Import data-sets</a>
                        <a class="dropdown-item" href="{{route('arules.list_data')}}">View association</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Sample Association
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{route('arules.sample_one')}}">Sample-one</a>
                        <a class="dropdown-item" href="{{route('arules.sample_two')}}">Sample-two</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#">Faqs</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
</div>