routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('pages.home');
//});
//
//Route::get('/', function () {
//    return view('welcome');
//});

//Route::get('/', function() {
//    return view('pages.home');
//});
//
////
//Route::get('about', function()
//{
//
//    return View::make('pages.contact');
//
//});
//
//

//Route::get('/', ['as' => 'index', 'uses' => 'RulesController@index']);
//Route::get('/data-sets/upload', ['as' => 'upload', 'uses' => 'RulesController@index']);


Route::group(['as' => 'arules.', 'prefix' => '/'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'RulesController@index']);
    Route::get('/data-sets/import', ['as' => 'import', 'uses' => 'DatasetController@index']);
    Route::post('/data-sets/send', ['as' => 'import_data', 'uses' => 'DatasetController@importDataSet']);
    Route::get('/data-sets/list', ['as' => 'list_data', 'uses' => 'DatasetController@listDatasets']);
    Route::get('/data-sets/sample-one', ['as' => 'sample_one', 'uses' => 'DatasetController@sampleOneAssociation']);
    Route::get('/data-sets/sample-two', ['as' => 'sample_two', 'uses' => 'DatasetController@sampleTwoAssociation']);

    Route::get('/data-sets/{slug}', ['as' => 'predict', 'uses' => 'DatasetController@predictAssociation']);
    Route::post('/data-sets/{slug}', ['as' => 'adjust_predict', 'uses' => 'DatasetController@AdjustPredictAssociation']);


});

resources/views/pages/contact.blade.php
@extends('layouts.default')

@section('content')

       i am the contact page

@endsection

resources/views/pages/import_datasets.blade.php
@extends('layouts.default')

@section('content')

    <div  class="container">
    <div class="row">
        <div class="col-md-8 col-sm-8 offset-md-2 offset-sm-2">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Import data sets</h4>
                    <h6 class="card-subtitle mb-2 text-muted">This must be a <em>comma separated value (csv)</em> file</h6>

                    <div class="alert"></div>

                    <p class="card-text">Start by entering the title and description of the data-set.
                        This is used to identify a data-set from other data-sets, uploaded differently.</p>
                    <form id="form" action="{{route('arules.import_data')}}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{--<label for="title">Title</label>--}}
                                    <input type="text" name="title" class="form-control" id="title" minlength="5" required aria-describedby="titleHelp" placeholder="Enter title">
                                    <small id="titleHelp" class="form-text text-muted">This is the title of the data-set you want to import.</small>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{--<label for="description">Description</label>--}}
                                    <input type="text" name="description" class="form-control" minlength="10" required id="description" aria-describedby="descriptionHelp" placeholder="Enter description">
                                    <small id="descriptionHelp" class="form-text text-muted">This is the description of the data-set you want to import.</small>
                                </div>
                            </div>

                        </div>


                        {{--<p>--}}
                        {{--@foreach($samples as $key=> $sample)--}}
                        {{--@foreach($sample as $key=> $itemsets)--}}
                        {{--{{($itemsets)}}--}}
                        {{--@endforeach--}}
                        {{--{{($sample[$key])}}<br/>--}}
                        {{--@endforeach--}}
                        {{--</p>--}}
                        {{--@foreach($associator->large as $key=> $i)--}}
                            {{--<br/>{{$loop->index}}--}}
                            {{--@foreach($i as $r)--}}
                                {{--<br/>--}}
                                {{--@foreach($r as $t)--}}
                                {{--{{$t}}--}}
                                {{--@endforeach--}}
                            {{--@endforeach--}}
                        {{--@endforeach--}}
                        <div class="form-group">
                            <label for="file">Pick the csv file to be uploaded</label>
                            <input type="file" required name="file" class="form-control-file" id="file">
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>

                </div>
            </div>
        </div>
    </div>

    </div>

@endsection
@section('extra-heads')
    @parent

@endsection

@section('extra-scripts')
    @parent

    <script>
        console.log($('#form'));
        $('.alert').css('display', 'none');
        var importurl = '<?= route('arules.import_data') ?>';
        $('#form').submit(function (e) {
            e.preventDefault();
            var form_data =  new FormData(this);

            $.ajax({
                type: 'post',
                url: importurl,
                data: form_data,
                catch: false,
                contentType: false,
                processData: false,
                success: function(xhr) {
                    //reset the form fields
                    if(xhr.status){
                        $('#form').trigger("reset");
                        $('.alert').removeClass('alert-danger');
                        $('.alert').addClass('alert-success');
                        $('.alert').css('display', 'block');
                        $('.alert').text(xhr.message);
                    }
                },
                error: function (xhr) {
                    $('.alert').removeClass('alert-success');
                    $('.alert').addClass('alert-danger');
                    $('.alert').css('display', 'block');
                    if(xhr.status==422){
                        $('.alert').html(xhr.responseJSON.message +":<br/> Make sure the file is csv");
                    }else{
                        $('.alert').text(xhr.message);
                    }
                }
            });
        });
    </script>
@endsection

resources/views/pages/index.blade.php
@extends('layouts.default')

@section('content')

       <div  class="container">
        <div class="row" style="background-color: white">
            <div class="col-md-6">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img class="d-block w-100" src="{{ asset('images/1.jpg') }}" alt="First slide">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Gather data</h5>
                                <p>Make the data available from the right source</p>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="{{ asset('images/2.jpg') }}" alt="Second slide">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Compute</h5>
                                <p>Apply association rule to the gathered data</p>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="{{ asset('images/3.jpg') }}" alt="Third slide">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Decision</h5>
                                <p>Make decision</p>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="{{ asset('images/4.jpg') }}" alt="Third slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="{{ asset('images/5.jpg') }}" alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                Association rule learning is a rule-based machine learning method for discovering
                interesting relations between variables in large databases. It is intended to identify
                strong rules discovered in databases using some measures of interestingness.
                <br/><br/>
                Based on the concept of strong rules, Rakesh Agrawal, Tomasz Imieliński and
                Arun Swami[2] introduced association rules for discovering regularities between
                products in large-scale transaction data recorded by point-of-sale (POS) systems in supermarkets.
            </div>

        </div>
    </div>

@endsection
@section('extra-heads')
    @parent

    @endsection

resources/views/pages/list_datasets.blade.php
@extends('layouts.default')

@section('content')

        <div  class="container">
        <h1 class="grey-text">List of data-sets</h1>
        <div class="row bg-white" style="{{count($datasets)?'':'display: none;'}}">
            <div class="col-md-12 col-sm-12">
                @foreach($datasets as $dataset)
                    <h4><a href="{{route("arules.predict",['slug'=>$dataset->slug]) }}">{{$dataset->title}}</a></h4>
                    <p>{{$dataset->description}}</p>
                    @endforeach
            </div>
            <div >
                {{$datasets->links()}}
            </div>
        </div>
        <div class="row" style="{{count($datasets)?'display: none;':''}} ">
            <div class="bg-white py-3 col-sm-12 col-md-12 grey-text text-lighten-1">
                No data-set uploaded
            </div>
        </div>

    </div>

@endsection
@section('extra-heads')
    @parent
<style>
    .grey-text{
        color: grey;
    }
</style>

@endsection

@section('extra-scripts')
    @parent

    <script>
        console.log($('#form'));
        var importurl = '<?= route('arules.import_data') ?>';
        $('#form').submit(function (e) {
            e.preventDefault();
            var form_data =  new FormData(this);
            console.log($('#form').serialize());
            console.log($('#file').val());
            $.ajax({
                type: 'post',
                url: importurl,
                data: form_data,
                catch: false,
                contentType: false,
                processData: false,
                success: function(xhr) {
                    //reset the form fields
                    $('#form').trigger("reset");
                    //$('#post_submitted_data').append(data);
                    // alert('Yeah!!!!');
                    //document.getElementById('#post_submitted_data').
                    //$('#post_submitted_data').trigger("reset");

                    ///{data = JSON.parse(data);}
                    //console.log(xhr);

                },
                error: function (xhr) {

                }
            });
        });
    </script>
@endsection

resources/views/pages/predict.blade.php
@extends('layouts.default')

@section('content')

        <div  class="container">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title" style="text-align: center;">List of transactions and frequent item-sets</h4>
                <h4 class="card-subtitle mb-2 text-muted">{{$dataset->title}}</h4>
                <h5 class="card-subtitle mb-2 text-muted">{{$dataset->description}}</h5>
                {{--<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>--}}
                <h6 class="card-subtitle mb-2 text-muted"></h6><br/>
                <form id="form" action="{{route('arules.adjust_predict', ['slug'=>$dataset->slug])}}" method="post" enctype="multipart/form-data">
                    {{ csrf_field() }}

                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <label for="title">Support (default (0.5) ): <span id="suplabel">{{$support}}</span></label>
                                <input type="range" name="support" class="form-control-range" id="support" aria-describedby="titleHelp" min="1" max="100" placeholder="Enter title">
                                <small id="supportHelp" class="form-text text-muted">Adjust the support value: <span style="font-weight: bold" id="supvalue"></span></small>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                                <label for="description">Confidence (default (0.5) ): <span id="conflabel">{{$confidence}}</span></label>
                                <input type="range" name="confidence" class="form-control-range" min="1" max="100" id="confidence" aria-describedby="descriptionHelp" placeholder="Enter description">
                                <small id="confidenceHelp" class="form-text text-muted">Adjust confidence value: <span style="font-weight: bold" id="confvalue"></span></small>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <button type="submit" id="btn" class="btn btn-primary">Adjust</button>
                            </div>
                        </div>

                    </div>
                    <div class="divider"></div>

                    <ul class="nav nav-pills mb-3 nav-fill" id="pills-tab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Transactions::: item-sets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Database passes::: Frequent item-sets</a>
                        </li>
                    </ul>

                    <div class="tab-content" id="pills-tabContent">
                        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                            <h6 class="card-subtitle mb-2 text-muted">Each line/row is a transaction containing itemsets</h6>
                            <table class="table table-sm table-dark .table-responsive table-striped table-hover">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Item-sets</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($samples as $key=> $sample)
                                    <tr>
                                        <th scope="row">{{$loop->index}}</th>
                                        <td>{{(implode(', ',$sample))}}</td>
                                    </tr>
                                @empty
                                    <h2>No transaction data-sets available! Import data-set to get started</h2>
                                @endforelse

                                </tbody>
                            </table>
                        </div>
                        <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                            <h6 class="card-subtitle mb-2 text-muted">Each table represent a database pass. The table contents is the results gotten after each database pass</h6>
                            @forelse($associator->large as $key=> $i)

                                #{{$loop->index+1}}
                                <table class="table table-sm table-dark .table-responsive table-striped table-hover">
                                    <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th class="{{$loop->last?'bg-primary':''}}" scope="col">{{$loop->last?'The most frequent item-sets':'Frequent item-sets'}}</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($i as $r)

                                        <?php $most=''; ?>
                                        @foreach($r as $t)
                                            @php @$most .= @$loop->last?$t.'':$t.', ' @endphp
                                        @endforeach

                                        <tr>
                                            <th scope="row">{{$loop->index}}</th>
                                            <td>{{$most}}</td>
                                        </tr>

                                    @endforeach
                                    </tbody>
                                </table>
                            @empty
                                <h2 style="text-align: center">Unable to determine the most frequent item-set(s)</h2>
                            @endforelse
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>

@endsection
@section('extra-heads')
    @parent

@endsection

@section('extra-scripts')
    @parent

    <script>

        $('form #support, form #confidence').on('change click mousemove', function () {
            var support = $('#support').val();
            var confidence = $('#confidence').val();
            $('#supvalue').text(support/100);
            $('#confvalue').text(confidence/100);
        });



    </script>
@endsection

resources/views/pages/sample_one.blade.php
@extends('layouts.default')

@section('content')

        <div  class="container">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title" style="text-align: center;">List of transactions and frequent item-sets</h4>
                <h4 class="card-subtitle mb-2 text-muted">{{$dataset['title']}}</h4>
                <h5 class="card-subtitle mb-2 text-muted">{{$dataset['description']}}</h5>
                {{--<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>--}}
                <h6 class="card-subtitle mb-2 text-muted"></h6><br/>
                <form id="form" action="{{route('arules.import_data')}}" method="post" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <ul class="nav nav-pills mb-3 nav-fill" id="pills-tab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Transactions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Database passes</a>
                        </li>
                    </ul>

                    <div class="tab-content" id="pills-tabContent">
                        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                            <h6 class="card-subtitle mb-2 text-muted">Each line/row is a transaction containing itemsets</h6>
                            <table class="table table-sm table-dark .table-responsive table-striped table-hover">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Item-sets</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($samples as $key=> $sample)
                                    <tr>
                                        <th scope="row">{{$loop->index}}</th>
                                        <td>{{(implode(', ',$sample))}}</td>
                                    </tr>

                                @endforeach

                                </tbody>
                            </table>
                        </div>
                        <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                            <h6 class="card-subtitle mb-2 text-muted">Each table represent a database pass. The table contents is the results gotten after each database pass</h6>
                            @foreach($associator->large as $key=> $i)

                                #{{$loop->index+1}}
                                <table class="table table-sm table-dark .table-responsive table-striped table-hover">
                                    <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th class="{{$loop->last?'bg-primary':''}}" scope="col">{{$loop->last?'The most frequent item-sets':'Frequent item-sets'}}</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($i as $r)

                                        <?php $most=''; ?>
                                        @foreach($r as $t)
                                            @php @$most .= @$loop->last?$t.'':$t.', ' @endphp
                                        @endforeach

                                        <tr>
                                            <th scope="row">{{$loop->index}}</th>
                                            <td>{{$most}}</td>
                                        </tr>

                                    @endforeach
                                    </tbody>
                                </table>
                            @endforeach
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>

@endsection
@section('extra-heads')
    @parent

@endsection

@section('extra-scripts')
    @parent

    <script>

    </script>
@endsection

resources/views/pages/sample_two.blade.php
@extends('layouts.default')

@section('content')

        <div  class="container">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title" style="text-align: center;">List of transactions and frequent item-sets</h4>
                <h4 class="card-subtitle mb-2 text-muted">{{$dataset['title']}}</h4>
                <h5 class="card-subtitle mb-2 text-muted">{{$dataset['description']}}</h5>
                {{--<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>--}}
                <h6 class="card-subtitle mb-2 text-muted"></h6><br/>
                <form id="form" action="{{route('arules.import_data')}}" method="post" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <ul class="nav nav-pills mb-3 nav-fill" id="pills-tab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Transactions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Database passes</a>
                        </li>
                    </ul>

                    <div class="tab-content" id="pills-tabContent">
                        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                            <h6 class="card-subtitle mb-2 text-muted">Each line/row is a transaction containing itemsets</h6>
                            <table class="table table-sm table-dark .table-responsive table-striped table-hover">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Item-sets</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($samples as $key=> $sample)
                                    <tr>
                                        <th scope="row">{{$loop->index}}</th>
                                        <td>{{(implode(', ',$sample))}}</td>
                                    </tr>

                                @endforeach

                                </tbody>
                            </table>
                        </div>
                        <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                            <h6 class="card-subtitle mb-2 text-muted">Each table represent a database pass. The table contents is the results gotten after each database pass</h6>
                            @foreach($associator->large as $key=> $i)

                                #{{$loop->index+1}}
                                <table class="table table-sm table-dark .table-responsive table-striped table-hover">
                                    <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th class="{{$loop->last?'bg-primary':''}}" scope="col">{{$loop->last?'The most frequent item-sets':'Frequent item-sets'}}</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($i as $r)

                                        <?php $most=''; ?>
                                        @foreach($r as $t)
                                            @php @$most .= @$loop->last?$t.'':$t.', ' @endphp
                                        @endforeach

                                        <tr>
                                            <th scope="row">{{$loop->index}}</th>
                                            <td>{{$most}}</td>
                                        </tr>

                                    @endforeach
                                    </tbody>
                                </table>
                            @endforeach
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>

@endsection
@section('extra-heads')
    @parent

@endsection

@section('extra-scripts')
    @parent

    <script>

    </script>
@endsection